### ISSUE TITLE
Jupyter Not Starting After Reboot

### ISSUE THREAD

**Issue by elbrinke** [jupyter/jupyter_server#24]
Hi, 

We are running the Jupyter server, had a reboot and the service is no longer running. 

Getting the following error:

```
[I 2018-08-10 11:31:11.380 JupyterHub app:622] Loading cookie_secret from /jupyterhub_cookie_secret
[D 2018-08-10 11:31:11.380 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
[E 2018-08-10 11:31:11.389 JupyterHub app:1296]
    Traceback (most recent call last):
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/app.py", line 1293, in launch_instance_async
        yield self.initialize(argv)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/app.py", line 1099, in initialize
        self.init_db()
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/app.py", line 700, in init_db
        **self.db_kwargs
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/orm.py", line 402, in new_session_factory
        Base.metadata.create_all(engine)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/sql/schema.py", line 3748, in create_all
        tables=tables)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
        conn._run_visitor(visitorcallable, element, **kwargs)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
        **kwargs).traverse_single(element)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
        return meth(obj, **kw)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 709, in visit_metadata
        [t for t in tables if self._can_create_table(t)])
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 709, in <listcomp>
        [t for t in tables if self._can_create_table(t)])
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 686, in _can_create_table
        table.name, schema=table.schema)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1139, in has_table
        connection, "table_info", table_name, schema=schema)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1480, in _get_table_pragma
        cursor = connection.execute(statement)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
        return self._execute_text(object, multiparams, params)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
        statement, parameters
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
        raise value.with_traceback(tb)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: 'PRAGMA table_info("hubs")']
    
[D 2018-08-10 11:31:11.392 JupyterHub application:642] Exiting application: jupyterhub
```
Can you please assist us with this? 

Best Regards
Eddy

**Comment by blink1073** [comment]
Hi @elbrinke, it looks like the `jupyterhub` Database got corrupted.  Does it work after a `jupyterhub upgrade-db`?

**Comment by elbrinke** [comment]
Hi @blink1073 , when i run "jupyterhub upgrade-db" I get the following; 

> bash: jupyterhub: command not found

**Comment by blink1073** [comment]
What is the command you are using to launch jupyterhub?

**Comment by elbrinke** [comment]
Current running: **jupyter --version 4.2.0**

**Comment by blink1073** [comment]
jupyterhub is separate from the root jupyter install.

**Comment by elbrinke** [comment]
We just run : 

`jupyter notebook `

**Comment by blink1073** [comment]
I'm confused because the output above says `I 2018-08-10 11:31:11.380 JupyterHub app:622]`, it should say something like `[I 05:04:36.885 NotebookApp]` for the notebook app.  Perhaps something else went wrong with the install.  Are you able to start from a clean environment?

**Comment by elbrinke** [comment]
```
root@jupyter:/opt/.virtualenvs/jupyter/bin# ./jupyterhub start
[I 2018-08-10 12:04:56.696 JupyterHub app:622] Loading cookie_secret from /opt/.virtualenvs/jupyter/bin/jupyterhub_cookie_secret
[W 2018-08-10 12:04:56.730 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2018-08-10 12:04:56.733 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2018-08-10 12:04:56.733 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-08-10 12:04:56.733 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2018-08-10 12:04:56.741 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[E 2018-08-10 12:04:56.744 JupyterHub app:963] Refusing to run JuptyterHub without SSL. If you are terminating SSL in another layer, pass --no-ssl to tell JupyterHub to allow the proxy to listen on HTTP.
```

**Comment by blink1073** [comment]
Great!  Are you asking where to go from here or is that working now?

**Comment by blink1073** [comment]
I'm no JupyterHub expert, can you please try your question here: https://github.com/jupyterhub/jupyterhub?

**Comment by Zsailer** [comment]
Closing this issue, since it's run stale. Feel free to reopen if you still have questions here.
