### ISSUE TITLE
Provide a fallback for templates

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter_server#301]
If a template exists in `jupyter_server`, we should fall back to it.  e.g. [`error.html`](https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/templates/error.html) here:

```python
    Traceback (most recent call last):
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/tornado/web.py", line 1218, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jupyter_server/base/handlers.py", line 511, in write_error
        html = self.render_template('error.html', **ns)
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jupyter_server/base/handlers.py", line 440, in render_template
        template = self.get_template(name)
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jupyter_server/extension/handler.py", line 12, in get_template
        return self.settings[env].get_template(name)
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
        template = self.loader.load(self, name, globals)
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jinja2/loaders.py", line 197, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: error.html
```

**Comment by Zsailer** [comment]
Fixed in #302
